- name: disable reddis
  ansible.builtin.command: dnf module disable redis -y

- name: enable redis
  ansible.builtin.command: dnf module enable redis:7 -y

- name: install redis
  ansible.builtin.dnf:
    name: redis
    state: present



- name: change 0.0.0.0
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: disable products mode 
  ansible.builtin.lineinfile:
    path: /etc/redis/redis.conf
    regexp: 'protected-mode'
    line: protected-mode no

- name: enable and start service
  ansible.builtin.service:
    name: redis
    state: started
    enabled: yes